language: java
jdk:
- oraclejdk8
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
notifications:
  slack:
    secure: Aa9DHLyn2f9FEkto/Z/ihezlDbb3SDGjXOnaV21FqlfwYlNnxhV24p9rGlhOJz7uI0M8+oRn6Tb76GSIQQ1icbfPXv6XEPqn1iSi3542f7DeZDMj57xsQ0q3G2rZR7r9HdoFFXXBprJ48Zj4rYLoS1SpyUu0KgCrNS4vna+v//U+N6WaYKqIsj97GyYqq16Y4OtSBscPFoRFh/n+qViyWEuqNWux9ELPfI1st4ZIc/TJkS3xXOJBknSuDebuIy4rx3mWU4QLWfv6vveL/4+Q7kV71c9j53GAw4gMourDBjgR4E8UzvpEzKC5n1RthBmMvD3R/fmzss0lXfAwP07Rw3TvtKbC3jsx5H/nIqS8py2TNSBMDYDy1EdWog3g6mm3BhdjDz7ux5XZjyE210cyl1GCjSD8KRbSQtwDoiBikekPvIxIw+/XjhrEcVJfRXFqXE0I5k7eOs0kAGaXcMws9AcCmupnEgefEzJYhPONRETOiTNtnijzwsPb0N3q+j6vvZYbvKK3iMv17n09RpvXb5P0LiDZb+VfzgEjCApSndPj3RkVpF5F3qwx7YqwrTmr27UT9TPINbOvnqDXG+CpJHEjiby9BSsY+GS9Onf8udUGpeR4KKW2X7ibuxe4W4KPcprYeJk0uZevN/qGUB9XovwdBVv35mxVyW/0D9i/42c=
